# swagger/user.yaml

openapi: 3.0.3
info:
  title: User API Documentation
  description: API documentation for user-related operations.
  version: 1.0.0
servers:
  - url: https://your-api-url.com
tags:
  - name: User
    description: Operations related to user management
paths:
  /api/user:
    get:
      tags:
        - User
      summary: Get user by ID
      description: Retrieve user details by their ID.
      operationId: getUserById
      parameters:
        - in: query
          name: userId
          required: true
          description: ID of the user to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  user:
                    type: object
                    # Define properties of the user object here based on your actual schema
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
