# swagger/contact-mail.yaml

openapi: 3.0.3
info:
  title: Contact Mail API Documentation
  description: API documentation for handling contact mail requests.
  version: 1.0.0
servers:
  - url: https://your-api-url.com
tags:
  - name: Contact Mail
    description: Operations related to handling contact mail
paths:
  /api/contact-mail:
    post:
      tags:
        - Contact Mail
      summary: Handle contact mail requests
      description: Route to handle contact mail requests.
      operationId: handleContactMail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                mobile:
                  type: string
                message:
                  type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: integer
        '400':
          description: One or more required fields are empty
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: integer
        '500':
          description: Error occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
